### ISSUE TITLE
Issue with compilation

### ISSUE THREAD

**Issue by Bestnetcraft** [RaRe-Technologies/w2v_server_googlenews#5]
I am getting this error:
 python3 w2v_server.py w2v_*.py
2019-03-26 12:34:06,601 : INFO : w2v_server:165 : <module>(MainThread) : running w2v_server.py w2v_server.py
Traceback (most recent call last):
  File "w2v_server.py", line 176, in <module>
    config_srv = Config(**cherrypy.lib.reprconf.Config(conf_file).get('global'))
  File "/home/admin/ai/miniconda/lib/python3.7/site-packages/cherrypy/lib/reprconf.py", line 119, in __init__
    self.update(file)
  File "/home/admin/ai/miniconda/lib/python3.7/site-packages/cherrypy/lib/reprconf.py", line 130, in update
    self._apply(Parser.load(config))
  File "/home/admin/ai/miniconda/lib/python3.7/site-packages/cherrypy/lib/reprconf.py", line 208, in load
    return Parser().dict_from_file(input) if is_file else input.copy()
  File "/home/admin/ai/miniconda/lib/python3.7/site-packages/cherrypy/lib/reprconf.py", line 196, in dict_from_file
    self.read(file)
  File "/home/admin/ai/miniconda/lib/python3.7/site-packages/cherrypy/lib/reprconf.py", line 168, in read
    self._read(fp, filename)
  File "/home/admin/ai/miniconda/lib/python3.7/configparser.py", line 1079, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
--------------------------------------
I have been trying to sort this issue for almost a week.  I would request any pointers to solve this issue.

**Comment by piskvorky** [comment]
Seems unrelated to this repo -- try contacting the libraries you see in your traceback (miniconda, cherrypy).
